[2024-08-11 16:00:12,412: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-11 16:00:12,420: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-11 16:00:12,422: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-11 16:00:12,423: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "c:\users\admin\desktop\project\kidneydiseaseclassification\src\cnnClassifier\utils\common.py", line 33, in read_yaml
    return ConfigBox(content)
  File "box\box.py", line 259, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 12, in <module>
    data_ingestion.main()
  File "c:\users\admin\desktop\project\kidneydiseaseclassification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 13, in main
    config = ConfigurationManager()
  File "c:\users\admin\desktop\project\kidneydiseaseclassification\src\cnnClassifier\config\configuration.py", line 15, in __init__
    self.params = read_yaml(params_filepath)
  File "C:\Users\Admin\anaconda3\envs\kidney\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "c:\users\admin\desktop\project\kidneydiseaseclassification\src\cnnClassifier\utils\common.py", line 35, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2024-08-11 16:02:07,826: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-11 16:02:07,830: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-11 16:02:07,831: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-11 16:02:07,832: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "c:\users\admin\desktop\project\kidneydiseaseclassification\src\cnnClassifier\utils\common.py", line 33, in read_yaml
    return ConfigBox(content)
  File "box\box.py", line 259, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 12, in <module>
    data_ingestion.main()
  File "c:\users\admin\desktop\project\kidneydiseaseclassification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 13, in main
    config = ConfigurationManager()
  File "c:\users\admin\desktop\project\kidneydiseaseclassification\src\cnnClassifier\config\configuration.py", line 15, in __init__
    self.params = read_yaml(params_filepath)
  File "C:\Users\Admin\anaconda3\envs\kidney\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "c:\users\admin\desktop\project\kidneydiseaseclassification\src\cnnClassifier\utils\common.py", line 35, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2024-08-11 16:20:16,417: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-11 16:20:16,420: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-11 16:20:16,422: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-11 16:20:16,423: INFO: common: created directory at: artifacts]
[2024-08-11 16:20:16,424: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-11 16:20:16,424: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-11 16:20:36,799: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-11 16:20:37,461: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-11 16:34:50,450: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-11 16:34:50,453: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-11 16:34:50,455: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-11 16:34:50,456: INFO: common: created directory at: artifacts]
[2024-08-11 16:34:50,457: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-11 16:34:50,458: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-11 16:35:15,990: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-11 16:35:16,566: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-11 21:27:32,179: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-11 21:27:32,186: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-11 21:27:32,188: INFO: common: created directory at: artifacts]
[2024-08-11 21:28:29,157: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-11 21:28:29,160: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-11 21:28:29,160: INFO: common: created directory at: artifacts]
[2024-08-11 21:28:38,670: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-11 21:28:38,675: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-11 21:28:38,677: INFO: common: created directory at: artifacts]
[2024-08-11 21:29:18,394: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-11 21:29:18,397: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-11 21:29:18,398: INFO: common: created directory at: artifacts]
[2024-08-11 21:29:18,399: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-11 21:29:44,550: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
