[2024-08-11 16:00:12,412: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-11 16:00:12,420: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-11 16:00:12,422: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-11 16:00:12,423: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "c:\users\admin\desktop\project\kidneydiseaseclassification\src\cnnClassifier\utils\common.py", line 33, in read_yaml
    return ConfigBox(content)
  File "box\box.py", line 259, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 12, in <module>
    data_ingestion.main()
  File "c:\users\admin\desktop\project\kidneydiseaseclassification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 13, in main
    config = ConfigurationManager()
  File "c:\users\admin\desktop\project\kidneydiseaseclassification\src\cnnClassifier\config\configuration.py", line 15, in __init__
    self.params = read_yaml(params_filepath)
  File "C:\Users\Admin\anaconda3\envs\kidney\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "c:\users\admin\desktop\project\kidneydiseaseclassification\src\cnnClassifier\utils\common.py", line 35, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2024-08-11 16:02:07,826: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-11 16:02:07,830: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-11 16:02:07,831: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-11 16:02:07,832: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "c:\users\admin\desktop\project\kidneydiseaseclassification\src\cnnClassifier\utils\common.py", line 33, in read_yaml
    return ConfigBox(content)
  File "box\box.py", line 259, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 12, in <module>
    data_ingestion.main()
  File "c:\users\admin\desktop\project\kidneydiseaseclassification\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 13, in main
    config = ConfigurationManager()
  File "c:\users\admin\desktop\project\kidneydiseaseclassification\src\cnnClassifier\config\configuration.py", line 15, in __init__
    self.params = read_yaml(params_filepath)
  File "C:\Users\Admin\anaconda3\envs\kidney\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "c:\users\admin\desktop\project\kidneydiseaseclassification\src\cnnClassifier\utils\common.py", line 35, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2024-08-11 16:20:16,417: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-11 16:20:16,420: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-11 16:20:16,422: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-11 16:20:16,423: INFO: common: created directory at: artifacts]
[2024-08-11 16:20:16,424: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-11 16:20:16,424: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-11 16:20:36,799: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-11 16:20:37,461: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-11 16:34:50,450: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-11 16:34:50,453: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-11 16:34:50,455: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-11 16:34:50,456: INFO: common: created directory at: artifacts]
[2024-08-11 16:34:50,457: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-11 16:34:50,458: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-11 16:35:15,990: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-11 16:35:16,566: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-11 21:27:32,179: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-11 21:27:32,186: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-11 21:27:32,188: INFO: common: created directory at: artifacts]
[2024-08-11 21:28:29,157: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-11 21:28:29,160: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-11 21:28:29,160: INFO: common: created directory at: artifacts]
[2024-08-11 21:28:38,670: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-11 21:28:38,675: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-11 21:28:38,677: INFO: common: created directory at: artifacts]
[2024-08-11 21:29:18,394: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-11 21:29:18,397: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-11 21:29:18,398: INFO: common: created directory at: artifacts]
[2024-08-11 21:29:18,399: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-11 21:29:44,550: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-11 22:12:05,328: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-08-11 22:12:05,332: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-11 22:12:05,337: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-11 22:12:05,338: INFO: common: created directory at: artifacts]
[2024-08-11 22:12:05,339: INFO: common: created directory at: artifacts/data_ingestion]
[2024-08-11 22:12:05,340: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-11 22:12:44,851: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-08-11 22:12:45,689: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-08-11 22:12:45,689: INFO: main: *******************]
[2024-08-11 22:12:45,690: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-08-11 22:12:45,693: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-11 22:12:45,697: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-11 22:12:45,698: INFO: common: created directory at: artifacts]
[2024-08-11 22:12:45,699: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-11 22:12:46,498: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-11 22:12:46,837: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-08-12 07:55:36,295: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-12 07:55:36,295: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-12 07:55:36,295: INFO: common: created directory at: artifacts]
[2024-08-12 07:58:05,018: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-12 07:58:05,022: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-12 07:58:05,023: INFO: common: created directory at: artifacts]
[2024-08-12 07:58:05,026: INFO: common: created directory at: artifacts\training]
[2024-08-12 13:12:20,451: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-12 13:12:20,465: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-12 13:12:20,468: INFO: common: created directory at: artifacts]
[2024-08-12 13:12:20,469: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-12 13:12:21,107: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-12 13:13:39,956: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-12 13:13:39,966: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-12 13:13:39,970: INFO: common: created directory at: artifacts]
[2024-08-12 13:13:39,975: INFO: common: created directory at: artifacts\training]
[2024-08-12 18:27:33,174: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-12 18:27:33,179: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-12 18:27:33,189: INFO: common: created directory at: artifacts]
[2024-08-12 18:27:33,191: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-08-12 18:27:33,755: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-08-12 18:27:59,304: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-12 18:27:59,304: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-12 18:27:59,304: INFO: common: created directory at: artifacts]
[2024-08-12 18:27:59,304: INFO: common: created directory at: artifacts\training]
[2024-08-13 09:58:09,055: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-13 09:58:09,074: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-13 09:58:09,076: INFO: common: created directory at: artifacts]
[2024-08-13 10:01:47,232: INFO: common: json file saved at: scores.json]
[2024-08-13 10:01:50,726: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-08-13 10:01:51,355: INFO: builder_impl: Assets written to: C:\Users\Admin\AppData\Local\Temp\tmpixobxifv\model\data\model\assets]
[2024-08-13 10:24:07,739: INFO: main: *******************]
[2024-08-13 10:24:07,740: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-08-13 10:24:07,743: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-13 10:24:07,745: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-13 10:24:07,746: INFO: common: created directory at: artifacts]
[2024-08-13 10:27:21,544: INFO: common: json file saved at: scores.json]
[2024-08-13 10:27:21,545: INFO: common: json file saved at: scores.json]
[2024-08-13 10:27:21,545: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-08-13 10:35:29,907: INFO: main: *******************]
[2024-08-13 10:35:29,907: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-08-13 10:35:29,910: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-13 10:35:29,912: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-13 10:35:29,913: INFO: common: created directory at: artifacts]
[2024-08-13 10:38:43,965: INFO: common: json file saved at: scores.json]
[2024-08-13 10:38:43,967: INFO: common: json file saved at: scores.json]
[2024-08-13 10:38:43,967: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-08-13 11:34:53,584: INFO: main: *******************]
[2024-08-13 11:34:53,600: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-08-13 11:34:53,600: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-13 11:34:53,600: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-13 11:34:53,600: INFO: common: created directory at: artifacts]
[2024-08-13 11:38:25,655: INFO: common: json file saved at: scores.json]
[2024-08-13 11:38:25,656: INFO: common: json file saved at: scores.json]
[2024-08-13 11:38:25,657: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-08-13 12:50:44,307: INFO: main: *******************]
[2024-08-13 12:50:44,308: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-08-13 12:50:44,310: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-13 12:50:44,313: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-13 12:50:44,314: INFO: common: created directory at: artifacts]
[2024-08-13 12:53:57,703: INFO: common: json file saved at: scores.json]
[2024-08-13 12:53:57,704: INFO: common: json file saved at: scores.json]
[2024-08-13 12:53:57,704: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-08-13 12:55:12,021: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-08-13 12:55:12,030: INFO: common: yaml file: params.yaml loaded successfully]
[2024-08-13 12:55:12,033: INFO: common: created directory at: artifacts]
[2024-08-13 12:58:48,628: INFO: common: json file saved at: scores.json]
[2024-08-13 12:58:48,741: WARNING: connectionpool: Retrying (Retry(total=4, connect=5, read=4, redirect=5, status=5)) after connection broken by 'ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)': /tdtscvt/Kidney-Disease-Classification.mlflow/api/2.0/mlflow/runs/create]
[2024-08-13 12:58:51,573: WARNING: save: Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-08-13 12:58:52,172: INFO: builder_impl: Assets written to: C:\Users\Admin\AppData\Local\Temp\tmpcmhbgnqo\model\data\model\assets]
[2024-08-13 21:04:40,976: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.17:8080]
[2024-08-13 21:04:40,977: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-08-13 21:05:24,260: INFO: _internal: 127.0.0.1 - - [13/Aug/2024 21:05:24] "GET / HTTP/1.1" 200 -]
[2024-08-13 21:05:39,523: ERROR: app: Exception on /predict [POST]]
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Admin\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Admin\anaconda3\envs\kidney\lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\Admin\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Admin\anaconda3\envs\kidney\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Admin\anaconda3\envs\kidney\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "app.py", line 44, in predictRoute
    result = clApp.classifier.predict()
  File "c:\users\admin\desktop\project\kidneydiseaseclassification\src\cnnClassifier\pipeline\prediction.py", line 16, in predict
    model = load_model(os.path.join("model", "model.h5"))
  File "C:\Users\Admin\anaconda3\envs\kidney\lib\site-packages\keras\saving\saving_api.py", line 212, in load_model
    return legacy_sm_saving_lib.load_model(
  File "C:\Users\Admin\anaconda3\envs\kidney\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "C:\Users\Admin\anaconda3\envs\kidney\lib\site-packages\keras\saving\legacy\save.py", line 230, in load_model
    raise IOError(
OSError: No file or directory found at model\model.h5
[2024-08-13 21:05:39,533: INFO: _internal: 127.0.0.1 - - [13/Aug/2024 21:05:39] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -]
[2024-08-13 21:08:27,102: INFO: _internal: 127.0.0.1 - - [13/Aug/2024 21:08:27] "GET / HTTP/1.1" 200 -]
[2024-08-13 21:08:38,925: INFO: _internal: 127.0.0.1 - - [13/Aug/2024 21:08:38] "POST /predict HTTP/1.1" 200 -]
[2024-08-13 21:08:44,902: INFO: _internal: 127.0.0.1 - - [13/Aug/2024 21:08:44] "POST /predict HTTP/1.1" 200 -]
[2024-08-13 21:08:49,598: INFO: _internal: 127.0.0.1 - - [13/Aug/2024 21:08:49] "POST /predict HTTP/1.1" 200 -]
[2024-08-13 21:08:57,791: INFO: _internal: 127.0.0.1 - - [13/Aug/2024 21:08:57] "POST /predict HTTP/1.1" 200 -]
[2024-08-13 21:09:05,534: WARNING: polymorphic_function: 5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000002C8F0734D30> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-08-13 21:09:05,534: INFO: _internal: 127.0.0.1 - - [13/Aug/2024 21:09:05] "POST /predict HTTP/1.1" 200 -]
[2024-08-13 21:09:10,697: WARNING: polymorphic_function: 6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000002C8F0620E50> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.]
[2024-08-13 21:09:10,697: INFO: _internal: 127.0.0.1 - - [13/Aug/2024 21:09:10] "POST /predict HTTP/1.1" 200 -]
[2024-08-13 21:10:02,336: INFO: _internal: 127.0.0.1 - - [13/Aug/2024 21:10:02] "POST /predict HTTP/1.1" 200 -]
[2024-08-13 21:10:14,025: INFO: _internal: 127.0.0.1 - - [13/Aug/2024 21:10:14] "POST /predict HTTP/1.1" 200 -]
[2024-08-13 21:10:19,703: INFO: _internal: 127.0.0.1 - - [13/Aug/2024 21:10:19] "POST /predict HTTP/1.1" 200 -]
[2024-08-13 21:10:30,061: INFO: _internal: 127.0.0.1 - - [13/Aug/2024 21:10:30] "POST /predict HTTP/1.1" 200 -]
[2024-08-13 21:10:34,025: INFO: _internal: 127.0.0.1 - - [13/Aug/2024 21:10:34] "POST /predict HTTP/1.1" 200 -]
[2024-08-13 21:10:38,020: INFO: _internal: 127.0.0.1 - - [13/Aug/2024 21:10:38] "POST /predict HTTP/1.1" 200 -]
[2024-08-13 21:10:43,067: INFO: _internal: 127.0.0.1 - - [13/Aug/2024 21:10:43] "POST /predict HTTP/1.1" 200 -]
[2024-08-13 21:10:48,994: INFO: _internal: 127.0.0.1 - - [13/Aug/2024 21:10:48] "POST /predict HTTP/1.1" 200 -]
[2024-08-13 21:11:01,599: INFO: _internal: 127.0.0.1 - - [13/Aug/2024 21:11:01] "POST /predict HTTP/1.1" 200 -]
[2024-08-13 21:11:28,043: INFO: _internal: 127.0.0.1 - - [13/Aug/2024 21:11:28] "POST /predict HTTP/1.1" 200 -]
[2024-08-13 21:11:37,985: INFO: _internal: 127.0.0.1 - - [13/Aug/2024 21:11:37] "POST /predict HTTP/1.1" 200 -]
[2024-08-13 21:11:51,823: INFO: _internal: 127.0.0.1 - - [13/Aug/2024 21:11:51] "POST /predict HTTP/1.1" 200 -]
[2024-08-13 21:11:57,317: INFO: _internal: 127.0.0.1 - - [13/Aug/2024 21:11:57] "POST /predict HTTP/1.1" 200 -]
[2024-08-19 21:05:04,157: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.0.7:8080]
[2024-08-19 21:05:04,159: INFO: _internal: [33mPress CTRL+C to quit[0m]
[2024-08-19 21:05:07,171: INFO: _internal: 127.0.0.1 - - [19/Aug/2024 21:05:07] "GET / HTTP/1.1" 200 -]
[2024-08-19 21:05:13,022: INFO: _internal: 127.0.0.1 - - [19/Aug/2024 21:05:13] "POST /predict HTTP/1.1" 200 -]
[2024-08-19 21:05:28,508: INFO: _internal: 127.0.0.1 - - [19/Aug/2024 21:05:28] "POST /predict HTTP/1.1" 200 -]
[2024-08-19 21:05:34,802: INFO: _internal: 127.0.0.1 - - [19/Aug/2024 21:05:34] "POST /predict HTTP/1.1" 200 -]
